"""add_marketplace_fields

Revision ID: b6c87dbdfc16
Revises: ffff73a1e51e
Create Date: 2026-04-11 14:16:13.507162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c87dbdfc16'
down_revision: Union[str, Sequence[str], None] = 'ffff73a1e51e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salons', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('salons', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('salons', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('salons', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('salons', sa.Column('price_range', sa.String(length=10), nullable=True))
    op.add_column('salons', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('services', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('staff', sa.Column('years_experience', sa.Integer(), nullable=True))
    op.add_column('staff', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('staff', sa.Column('specialties', sa.JSON(), nullable=True))
    # op.create_unique_constraint('uq_staff_service', 'staff_services', ['staff_id', 'service_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_staff_service', 'staff_services', type_='unique')
    op.drop_column('staff', 'specialties')
    op.drop_column('staff', 'rating')
    op.drop_column('staff', 'years_experience')
    op.drop_column('services', 'category')
    op.drop_column('services', 'description')
    op.drop_column('salons', 'tags')
    op.drop_column('salons', 'price_range')
    op.drop_column('salons', 'review_count')
    op.drop_column('salons', 'rating')
    op.drop_column('salons', 'description')
    op.drop_column('salons', 'city')
    # ### end Alembic commands ###
